### PR TITLE
If IP4_NAMESERVERS are unset then pull the value from /etc/resolv.conf

### LINKED ISSUE #5131: /etc/origin/node/resolv.conf: no such file or directory
#### Description

> With ansible-2.3.1.0-3 and openshift-ansible-3.6.173.0.5-5, install failed when start node service.

##### Version

```
# ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
# rpm -q atomic-openshift-utils openshift-ansible
atomic-openshift-utils-3.6.173.0.5-5.el7.noarch
openshift-ansible-3.6.173.0.5-5.el7.noarch
```

##### Steps To Reproduce
1. add 'openshift_disable_check=disk_availability,memory_availability,docker_image_availability,docker_storage' to ansible playbooks
2. execute the installation

##### Expected Results
No error is reported and complete the installation.

##### Observed Results
Install failed and the log is as following:
```
-- Unit atomic-openshift-node.service has begun starting up.
Aug 17 19:27:24 localhost.localdomain dnsmasq[30702]: setting upstream servers from DBus
Aug 17 19:27:24 localhost.localdomain dnsmasq[30702]: using nameserver 127.0.0.1#53 for domain in-addr.arpa
Aug 17 19:27:24 localhost.localdomain dnsmasq[30702]: using nameserver 127.0.0.1#53 for domain cluster.local
Aug 17 19:27:24 localhost.localdomain atomic-openshift-node[34559]: I0817 19:27:24.378039   34559 start_node.go:251] Reading node configuration from /etc/o
rigin/node/node-config.yaml
Aug 17 19:27:24 localhost.localdomain atomic-openshift-node[34559]: I0817 19:27:24.394623   34559 node.go:123] Initializing SDN node of type "redhat/opensh
ift-ovs-subnet" with configured hostname "192.168.96.52" (IP ""), iptables sync period "30s"
Aug 17 19:27:24 localhost.localdomain atomic-openshift-node[34559]: I0817 19:27:24.399508   34559 docker.go:364] Connecting to docker on unix:///var/run/do
cker.sock
Aug 17 19:27:24 localhost.localdomain atomic-openshift-node[34559]: I0817 19:27:24.399546   34559 docker.go:384] Start docker client with request timeout=2
m0s
Aug 17 19:27:24 localhost.localdomain atomic-openshift-node[34559]: W0817 19:27:24.401036   34559 cni.go:157] Unable to update cni config: No networks foun
d in /etc/cni/net.d
Aug 17 19:27:24 localhost.localdomain atomic-openshift-node[34559]: F0817 19:27:24.411615   34559 start_node.go:140] could not start DNS, unable to read co
nfig file: open /etc/origin/node/resolv.conf: no such file or directory
Aug 17 19:27:24 localhost.localdomain systemd[1]: atomic-openshift-node.service: main process exited, code=exited, status=255/n/a
Aug 17 19:27:24 localhost.localdomain dnsmasq[30702]: setting upstream servers from DBus
Aug 17 19:27:24 localhost.localdomain systemd[1]: Failed to start OpenShift Node.
``` 

##### Additional Information

The OS is  rhel 7.4.

### PR DESCRIPTION
**Pull request by sdodson**
This will happen whenever someone has directly modified /etc/resolv.conf

Should fix https://github.com/openshift/openshift-ansible/issues/4935
Fixes #5131
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1480438

### CODE REVIEW

**Comment by sdodson** [comment]
aos-ci-test

File: roles/openshift_node_dnsmasq/files/networkmanager/99-origin-dns.sh [hunk 1]
```diff
@@ -61,35 +59,40 @@ EOF
...
-    # and /etc/origin/node/resolv.conf in their respective formats
-    for ns in ${IP4_NAMESERVERS}; do
-      if [[ ! -z $ns ]]; then
-        echo "server=${ns}" >> $UPSTREAM_DNS_TMP
-        echo "nameserver ${ns}" >> $NEW_NODE_RESOLV_CONF
+    # If network manager doesn't know about the nameservers then the best
+    # we can do is grab them from /etc/resolv.conf but only if we've got no
+    # watermark
+    if ! grep -q '99-origin-dns.sh' /etc/resolv.conf; then
+      if ! [[ -n "${IP4_NAMESERVERS}" && "${IP4_NAMESERVERS}" != "${def_route_ip}" ]]; then
```
Comment (ewolinetz) [inline roles/openshift_node_dnsmasq/files/networkmanager/99-origin-dns.sh]: can't this be rewritten as `if [[ -z "${IP4_NAMESERVERS}" || "${IP4_NAMESERVERS}" == "${def_route_ip}" ]]; then` ? that seems more obvious to me as to what we're checking for rather than negating the `if` afterwards...

Comment (sdodson) [inline roles/openshift_node_dnsmasq/files/networkmanager/99-origin-dns.sh]: Yeah, I'll update it, thanks.

**Comment by sdodson** [comment]
aos-ci-test

**Comment by sdodson** [comment]
[test]

**Comment by sdodson** [comment]
[merge]

**Comment by sdodson** [comment]
[merge]
